from faker import Faker
fake = Faker()

<start> ::= <paragraph>

<paragraph> ::= ((<composed_S>){4,10} <S>'. '){5,15}

<composed_S>::= <S> " " <C> " " <S> " "

<S> ::= <NP> " " <VP> 

<NP> ::= <Det> " " <N> | <Det> " " <Adj> " " <N>

<VP> ::= <Verb> " " <NP>

<Verb> ::= <Aux> " " <V>

<C> ::= "and" 
       | "but" 
       | "or" 
       | "nor" 
       | "for" 
       | "so" 
       | "yet"
       | "whenever"
       | "although" 
       | "because" 
       | "since" 
       | "unless" 
       | "while" 
       | "whereas"
       | "if" 
       | "then" 
       | "whether" 
       | "after" 
       | "before" 
       | "once" 
       | "until" 
       | "when"
       | "where" 
       | "wherever" 
       | "as" 
       | "though" 
       | "even though" 
       | "provided that"

<Det> ::= "the" 
         | "a" 
         | "an" 
         | "this" 
         | "that" 
         | "these" 
         | "those" 
         | "some" 
         | "any" 
         | "each" 
         | "every" 
         | "no"
         | "either" 
         | "neither"
         | "my" 
         | "your" 
         | "his" 
         | "her" 
         | "its" 
         | "our" 
         | "their"

<N> ::= "experiment"
       | "analysis"
       | "theory"
       | "phenomenon"
       | "property"
       | "model"
       | "data"
       | "variable"
       | "equation"
       | "method"
       | "hypothesis"
       | "mechanism"
       | "procedure"
       | "technique"
       | "instrument"
       | "measurement"
       | "dataset"
       | "observation"
       | "structure"
       | "result"
       | "specimen"
       | "research"
       | "outcome"
       | "system"
       | "component"
       | "simulation"
       | "conclusion"
       | "anomaly"
       | "algorithm"
       | <name>
       | <country>

<name> ::= <printable>+ := fake.first_name()

<country> ::= <printable>+ := fake.country()

<job> ::= <printable>+ := fake.job().lower()

<Aux> ::= "be" 
         | "am" 
         | "is" 
         | "are" 
         | "was" 
         | "were" 
         | "been" 
         | "being" 
         | "have" 
         | "has" 
         | "had" 
         | "do"
         | "does" 
         | "did" 
         | "can" 
         | "could" 
         | "will" 
         | "would" 
         | "shall" 
         | "should"
         | "may"
         | "might"
         | "must"

<V> ::= "analyze"
       | "observe"
       | "examine"
       | "measure"
       | "investigate"
       | "assess"
       | "quantify"
       | "evaluate"
       | "estimate"
       | "demonstrate"
       | "establish"
       | "postulate"
       | "theorize"
       | "prove"
       | "disprove"
       | "verify"
       | "validate"
       | "conduct"
       | "synthesize"
       | "decompose"
       | "characterize"
       | "calculate"
       | "correlate"
       | "simulate"
       | "approximate"
       | "derive"
       | "conclude"
       | "model"
       | "formulate"
       | "predict"
       | "argue"
       | "hypothesize"
       | "survey"
       | "associate"
       | "apply"
       | "reproduce"
       | "replicate"
       | "compare"
       | "distinguish"
       | "indicate"
       | "troubleshoot"

<Adj> ::= "significant"
        | "theoretical"
        | "experimental"
        | "empirical"
        | "anomalous"
        | "systematic"
        | "observational"
        | "quantitative"
        | "qualitative"
        | "computational"
        | "remarkable"
        | "microscopic"
        | "macroscopic"
        | "random"
        | "deterministic"
        | "synthetic"
        | "analytic"
        | "critical"
        | "consistent"
        | "inconsistent"
        | <color>

<color> ::= <printable>+ := fake.safe_color_name()